name: market_ledger
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Database
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # State Management
  provider: 6.1.5+1
  
  # PDF Generation for printing invoices
  pdf: ^3.10.4
  printing: ^5.11.1
  
  # Date handling
  intl: ^0.19.0
  
  # Local storage for settings
  path_provider: 2.1.5
  shared_preferences: 2.5.3

  # Ø§Ù„Ø­Ø²Ù…Ø© Ø§Ù„ØªÙŠ ØªÙ…ÙƒÙ† sqflite Ù…Ù† Ø§Ù„Ø¹Ù…Ù„ Ø¹Ù„Ù‰ Ø³Ø·Ø­ Ø§Ù„Ù…ÙƒØªØ¨ ÙˆØ§Ù„ÙˆÙŠØ¨
  sqflite_common_ffi: ^2.3.0+2 

   # Ø§Ù„Ø­Ø²Ù…Ø© Ø§Ù„Ø¥Ø¶Ø§ÙÙŠØ© Ø§Ù„Ù…Ø·Ù„ÙˆØ¨Ø© Ù„Ù„ÙˆÙŠØ¨
  sqflite_common_ffi_web: ^0.4.2+2

  # Ø§Ù„Ù„ÙˆØºÙˆ
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/db/alhal_store.db

# ðŸ‘‡ Ù‚Ø³Ù… Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚
flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  #adaptive_icon_background: "#FFFFFF"